### ISSUE TITLE
setup does not start and gives error messages

### ISSUE THREAD

**Issue by mountaround** [jorgeluiscarrillo/arch-setup#5]
@jorgeluiscarrillo 

There are no errors when you run these two lines:
`pacman -Sy git`
`git clone https://github.com/jorgeluiscarrillo/arch-setup`

But with the next/last:
`cd arch-setup/ && ./setup`
there are various error messages and setup does not start.
Could you do a testinstall to find the bug? I can't get any further at this point.

System: Host (no vm)
Arch-ISO: Latest arch-iso-image 08/2020

**Comment by jorgeluiscarrillo** [comment]
Looks like Arch recently removed the `dialog` package from the live ISO. Installing dialog will be a pre-requisite from now on.
